# Generated by Django 3.2 on 2023-10-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('condicion', models.IntegerField(choices=[(1, 'OPERATIVO'), (2, 'INOPERATIVO')], default=1)),
            ],
            options={
                'db_table': 'tbl_equipo',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.IntegerField(choices=[(1, 'INGRESO'), (2, 'SALIDA')], default=1)),
                ('motivo', models.IntegerField(choices=[(1, 'ASIGNACION'), (2, 'PRESTAMO'), (3, 'DEVOLUCION'), (4, 'BAJA')], default=1)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha', models.DateField(auto_now=True)),
                ('saldo', models.IntegerField(null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.equipo')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.laboratorio')),
            ],
            options={
                'db_table': 'tbl_movimiento',
            },
        ),
    ]
